version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.6.2
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    volumes: 
      - ./elasticsearch/data:/usr/share/elasticsearch/data
  kibana:
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    image: docker.elastic.co/kibana/kibana-oss:7.6.2
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200